name: npm Update Packages

inputs:
  cron-schedule:
    description: 'Cron schedule'
    required: true
    default: '0 0 * * *'

  package-lock:
    description: 'Update package-lock.json'
    required: true
    default: true

  pr-title:
    description: 'PR title'
    required: true
    default: 'chore(dependencies): bump'

  pr-per:
    description: 'PR per update'
    required: true
    default: true

  pr-labels:
    description: 'PR labels'
    required: false
    default: ""

on:
  schedule:
    - cron: ${{ inputs.cron-schedule }} || ''
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-packages:
    name: Update Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set Up
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        using: "composite"
        shell: bash
        run: ./src/update-package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_PACKAGES }}
          PR_TITLE: ${{ inputs.pr-title }}
          PACKAGE_LOCK: ${{ inputs.package-lock }}
          PR_PER: ${{ inputs.pr-per }}
          PR_LABELS: ${{ inputs.pr-labels }}

      - name: Outputs
        run: |
          [ "${{ steps.run.output.STATUS }}" = 1 ] && echo "${{ steps.run.output.LOG }}" >> "$GITHUB_STEP_SUMMARY"
          [ "${{ steps.run.output.STATUS }}" = 0 ] && echo "Packages are already up to date" >> "$GITHUB_STEP_SUMMARY"
