name: Local Action Test

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Run Local Action
        uses: ./

      - name: Test
        run: |
          set -x
